In [43]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [44]:
data=pd.read_csv(r"C:\Users\ankit\Downloads\P74-Project-1\Car_Purchasing_Data.csv", encoding = 'ISO-8859-1')



In [45]:
x = data.drop(['Customer Name','Customer e-mail','Country','Car Purchase Amount'],axis=1)
y = data['Car Purchase Amount']





In [48]:
print (x)


[[0.         0.4370344  0.53515116 0.57836085 0.22342985]
 [0.         0.41741247 0.58308616 0.476028   0.52140195]
 [1.         0.46305795 0.42248189 0.55579674 0.63108896]
 ...
 [1.         0.67886994 0.61110973 0.52822145 0.75972584]
 [1.         0.78321017 0.37264988 0.69914746 0.3243129 ]
 [1.         0.53462305 0.51713347 0.46690159 0.45198622]]


In [49]:
print(y)

0      35321.45877
1      45115.52566
2      42925.70921
3      67422.36313
4      55915.46248
          ...     
495    48901.44342
496    31491.41457
497    64147.28888
498    45442.15353
499    45107.22566
Name: Car Purchase Amount, Length: 500, dtype: float64


In [50]:
x.shape


(500, 5)

In [51]:
y.shape

(500,)

In [57]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
x = sc.fit_transform(x)
y=y.values.reshape(-1,1)
y = sc.fit_transform(y)


In [61]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [79]:
import tensorflow.keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model=Sequential()
model.add(Dense(60,input_dim=5,activation='relu'))
model.add(Dense(30,activation='relu'))

model.add(Dense(1,activation='linear'))




In [80]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_14 (Dense)            (None, 60)                360       
                                                                 
 dense_15 (Dense)            (None, 30)                1830      
                                                                 
 dense_16 (Dense)            (None, 1)                 31        
                                                                 
Total params: 2221 (8.68 KB)
Trainable params: 2221 (8.68 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [81]:
model.compile(optimizer='adam',loss='mean_squared_error')

In [82]:
validTepochs_hist=model.fit(x_train,y_train,epochs=20,batch_size=25,verbose=1,validation_split=0.2)

Epoch 1/20
12/12 [==============================] - 1s 23ms/step - loss: 0.1126 - val_loss: 0.0441
Epoch 2/20
12/12 [==============================] - 0s 7ms/step - loss: 0.0217 - val_loss: 0.0193
Epoch 3/20
12/12 [==============================] - 0s 6ms/step - loss: 0.0205 - val_loss: 0.0159
Epoch 4/20
12/12 [==============================] - 0s 8ms/step - loss: 0.0146 - val_loss: 0.0170
Epoch 5/20
12/12 [==============================] - 0s 9ms/step - loss: 0.0132 - val_loss: 0.0140
Epoch 6/20
12/12 [==============================] - 0s 11ms/step - loss: 0.0113 - val_loss: 0.0119
Epoch 7/20
12/12 [==============================] - 0s 8ms/step - loss: 0.0098 - val_loss: 0.0099
Epoch 8/20
12/12 [==============================] - 0s 9ms/step - loss: 0.0080 - val_loss: 0.0084
Epoch 9/20
12/12 [==============================] - 0s 8ms/step - loss: 0.0066 - val_loss: 0.0068
Epoch 10/20
12/12 [==============================] - 0s 9ms/step - loss: 0.0052 - val_loss: 0.0054
Epoch 11/20
12/12

In [86]:
a = np.array([1, 50, 50000, 10000, 600000])

# Reshape 'a' to be a 2D array (batch size of 1)
a = a.reshape(1, -1)

# Predict using the model
b = model.predict(a)

print(b)

1/1 [==============================] - 0s 94ms/step
[[213407.83]]


In [87]:
# Evaluate the model on the test data
test_loss = model.evaluate(x_test, y_test)
print(f"Test loss: {test_loss}")


4/4 [==============================] - 0s 3ms/step - loss: 7.1146e-04
Test loss: 0.0007114604813978076
